[2024-08-22T13:09:31.952+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-22T13:09:33.128+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: update_insider_deals_in_s3_monthly.fetch_all_insider_deals manual__2024-08-22T13:09:26.761360+00:00 [queued]>
[2024-08-22T13:09:33.146+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: update_insider_deals_in_s3_monthly.fetch_all_insider_deals manual__2024-08-22T13:09:26.761360+00:00 [queued]>
[2024-08-22T13:09:33.147+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-22T13:09:33.174+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): fetch_all_insider_deals> on 2024-08-22 13:09:26.761360+00:00
[2024-08-22T13:09:33.199+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=4651) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-22T13:09:33.202+0000] {standard_task_runner.py:64} INFO - Started process 4673 to run task
[2024-08-22T13:09:33.208+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'update_insider_deals_in_s3_monthly', 'fetch_all_insider_deals', 'manual__2024-08-22T13:09:26.761360+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/load_insider_deals_raw.py', '--cfg-path', '/tmp/tmpm208816r']
[2024-08-22T13:09:33.213+0000] {standard_task_runner.py:91} INFO - Job 42: Subtask fetch_all_insider_deals
[2024-08-22T13:09:33.251+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-08-22T13:09:33.335+0000] {task_command.py:426} INFO - Running <TaskInstance: update_insider_deals_in_s3_monthly.fetch_all_insider_deals manual__2024-08-22T13:09:26.761360+00:00 [running]> on host fa4e08fee2f6
[2024-08-22T13:09:33.514+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='update_insider_deals_in_s3_monthly' AIRFLOW_CTX_TASK_ID='fetch_all_insider_deals' AIRFLOW_CTX_EXECUTION_DATE='2024-08-22T13:09:26.761360+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-22T13:09:26.761360+00:00'
[2024-08-22T13:09:33.516+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-22T13:09:34.030+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-22T13:09:34.033+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/load_insider_deals_raw.py", line 60, in fetch_all_insider_deals
    symbol = symbol_info['ticker']
             ~~~~~~~~~~~^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
[2024-08-22T13:09:34.063+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=update_insider_deals_in_s3_monthly, task_id=fetch_all_insider_deals, run_id=manual__2024-08-22T13:09:26.761360+00:00, execution_date=20240822T130926, start_date=20240822T130933, end_date=20240822T130934
[2024-08-22T13:09:34.082+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 42 for task fetch_all_insider_deals (string indices must be integers, not 'str'; 4673)
[2024-08-22T13:09:34.104+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-22T13:09:34.135+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-22T13:09:34.140+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
