[2024-08-22T14:23:26.623+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-22T14:23:26.761+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: update_company_news_in_s3_week.fetch_company_news manual__2024-08-22T14:23:16.248590+00:00 [queued]>
[2024-08-22T14:23:26.774+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: update_company_news_in_s3_week.fetch_company_news manual__2024-08-22T14:23:16.248590+00:00 [queued]>
[2024-08-22T14:23:26.776+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-22T14:23:26.794+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): fetch_company_news> on 2024-08-22 14:23:16.248590+00:00
[2024-08-22T14:23:26.809+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=15963) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-22T14:23:26.807+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'update_company_news_in_s3_week', 'fetch_company_news', 'manual__2024-08-22T14:23:16.248590+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/load_news_raw.py', '--cfg-path', '/tmp/tmparlvwnmo']
[2024-08-22T14:23:26.810+0000] {standard_task_runner.py:64} INFO - Started process 15980 to run task
[2024-08-22T14:23:26.811+0000] {standard_task_runner.py:91} INFO - Job 57: Subtask fetch_company_news
[2024-08-22T14:23:26.828+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-08-22T14:23:26.873+0000] {task_command.py:426} INFO - Running <TaskInstance: update_company_news_in_s3_week.fetch_company_news manual__2024-08-22T14:23:16.248590+00:00 [running]> on host fa4e08fee2f6
[2024-08-22T14:23:27.253+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='update_company_news_in_s3_week' AIRFLOW_CTX_TASK_ID='fetch_company_news' AIRFLOW_CTX_EXECUTION_DATE='2024-08-22T14:23:16.248590+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-22T14:23:16.248590+00:00'
[2024-08-22T14:23:27.260+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-22T14:24:02.041+0000] {local_task_job_runner.py:313} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-08-22T14:24:02.072+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-08-22T14:24:02.104+0000] {process_utils.py:132} INFO - Sending 15 to group 15980. PIDs of all processes in the group: [15980]
[2024-08-22T14:24:02.105+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 15980
[2024-08-22T14:24:02.107+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-08-22T14:24:02.112+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-22T14:24:02.198+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=15980, status='terminated', exitcode=0, started='14:23:26') (15980) terminated with exit code 0
