[2024-08-22T11:26:06.215+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-22T11:26:06.242+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: update_stock_data_hour_into_s3_123.update_parquet_file_1 manual__2024-08-22T11:24:13.137425+00:00 [queued]>
[2024-08-22T11:26:06.255+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: update_stock_data_hour_into_s3_123.update_parquet_file_1 manual__2024-08-22T11:24:13.137425+00:00 [queued]>
[2024-08-22T11:26:06.256+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-22T11:26:06.271+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): update_parquet_file_1> on 2024-08-22 11:24:13.137425+00:00
[2024-08-22T11:26:06.283+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'update_stock_data_hour_into_s3_123', 'update_parquet_file_1', 'manual__2024-08-22T11:24:13.137425+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/load_data_into_s3_hour.py', '--cfg-path', '/tmp/tmp0nr5aluo']
[2024-08-22T11:26:06.286+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=8233) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-22T11:26:06.287+0000] {standard_task_runner.py:91} INFO - Job 23: Subtask update_parquet_file_1
[2024-08-22T11:26:06.287+0000] {standard_task_runner.py:64} INFO - Started process 8235 to run task
[2024-08-22T11:26:06.310+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-08-22T11:26:06.373+0000] {task_command.py:426} INFO - Running <TaskInstance: update_stock_data_hour_into_s3_123.update_parquet_file_1 manual__2024-08-22T11:24:13.137425+00:00 [running]> on host fa4e08fee2f6
[2024-08-22T11:26:06.692+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='update_stock_data_hour_into_s3_123' AIRFLOW_CTX_TASK_ID='update_parquet_file_1' AIRFLOW_CTX_EXECUTION_DATE='2024-08-22T11:24:13.137425+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-22T11:24:13.137425+00:00'
[2024-08-22T11:26:06.694+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-22T11:26:06.862+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-22T11:26:06.865+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/load_data_into_s3_hour.py", line 108, in update_parquet_file_1
    combined_df_1 = combined_df.drop_duplicates(subset=['date', 'symbol'],keep='last').copy()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 6566, in drop_duplicates
    result = self[-self.duplicated(subset, keep=keep)]
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 6698, in duplicated
    raise KeyError(Index(diff))
KeyError: Index(['date'], dtype='object')
[2024-08-22T11:26:06.907+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=update_stock_data_hour_into_s3_123, task_id=update_parquet_file_1, run_id=manual__2024-08-22T11:24:13.137425+00:00, execution_date=20240822T112413, start_date=20240822T112606, end_date=20240822T112606
[2024-08-22T11:26:06.922+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 23 for task update_parquet_file_1 (Index(['date'], dtype='object'); 8235)
[2024-08-22T11:26:06.945+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-22T11:26:06.962+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-22T11:26:06.968+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
