[2024-08-22T10:24:21.371+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-22T10:24:21.394+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trino_to_parquet_minio.create_schema_and_table manual__2024-08-22T10:24:19.546301+00:00 [queued]>
[2024-08-22T10:24:21.402+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trino_to_parquet_minio.create_schema_and_table manual__2024-08-22T10:24:19.546301+00:00 [queued]>
[2024-08-22T10:24:21.403+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-22T10:24:21.414+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): create_schema_and_table> on 2024-08-22 10:24:19.546301+00:00
[2024-08-22T10:24:21.421+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=300) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-22T10:24:21.423+0000] {standard_task_runner.py:64} INFO - Started process 302 to run task
[2024-08-22T10:24:21.422+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'trino_to_parquet_minio', 'create_schema_and_table', 'manual__2024-08-22T10:24:19.546301+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/get_data_from_s3_by_trino.py', '--cfg-path', '/tmp/tmp1wzofnfp']
[2024-08-22T10:24:21.424+0000] {standard_task_runner.py:91} INFO - Job 2: Subtask create_schema_and_table
[2024-08-22T10:24:21.438+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-08-22T10:24:21.469+0000] {task_command.py:426} INFO - Running <TaskInstance: trino_to_parquet_minio.create_schema_and_table manual__2024-08-22T10:24:19.546301+00:00 [running]> on host fa4e08fee2f6
[2024-08-22T10:24:21.553+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='trino_to_parquet_minio' AIRFLOW_CTX_TASK_ID='create_schema_and_table' AIRFLOW_CTX_EXECUTION_DATE='2024-08-22T10:24:19.546301+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-22T10:24:19.546301+00:00'
[2024-08-22T10:24:21.554+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-22T10:24:21.564+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-22T10:24:21.571+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/get_data_from_s3_by_trino.py", line 45, in create_schema_and_table
    conn = trino_hook.get_conn()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/trino/hooks/trino.py", line 98, in get_conn
    db = self.get_connection(self.trino_conn_id)  # type: ignore[attr-defined]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `trino_default` isn't defined
[2024-08-22T10:24:21.584+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=trino_to_parquet_minio, task_id=create_schema_and_table, run_id=manual__2024-08-22T10:24:19.546301+00:00, execution_date=20240822T102419, start_date=20240822T102421, end_date=20240822T102421
[2024-08-22T10:24:21.596+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 2 for task create_schema_and_table (The conn_id `trino_default` isn't defined; 302)
[2024-08-22T10:24:21.638+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-22T10:24:21.657+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-22T10:24:21.661+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
