[2024-08-17T15:45:40.897+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-17T15:45:40.938+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: csv_to_parquet_minio_no_partition.csv_to_parquet_and_upload manual__2024-08-17T15:45:39.428874+00:00 [queued]>
[2024-08-17T15:45:40.952+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: csv_to_parquet_minio_no_partition.csv_to_parquet_and_upload manual__2024-08-17T15:45:39.428874+00:00 [queued]>
[2024-08-17T15:45:40.953+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-17T15:45:40.971+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): csv_to_parquet_and_upload> on 2024-08-17 15:45:39.428874+00:00
[2024-08-17T15:45:40.981+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'csv_to_parquet_minio_no_partition', 'csv_to_parquet_and_upload', 'manual__2024-08-17T15:45:39.428874+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/load_data_into_s3.py', '--cfg-path', '/tmp/tmp6w33j8mu']
[2024-08-17T15:45:40.984+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=3293) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-17T15:45:40.985+0000] {standard_task_runner.py:91} INFO - Job 34: Subtask csv_to_parquet_and_upload
[2024-08-17T15:45:40.985+0000] {standard_task_runner.py:64} INFO - Started process 3302 to run task
[2024-08-17T15:45:41.005+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-08-17T15:45:41.084+0000] {task_command.py:426} INFO - Running <TaskInstance: csv_to_parquet_minio_no_partition.csv_to_parquet_and_upload manual__2024-08-17T15:45:39.428874+00:00 [running]> on host 09ead0534f89
[2024-08-17T15:45:41.298+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='csv_to_parquet_minio_no_partition' AIRFLOW_CTX_TASK_ID='csv_to_parquet_and_upload' AIRFLOW_CTX_EXECUTION_DATE='2024-08-17T15:45:39.428874+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-17T15:45:39.428874+00:00'
[2024-08-17T15:45:41.300+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-17T15:45:41.304+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-17T15:45:41.305+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/load_data_into_s3.py", line 41, in csv_to_parquet_and_upload
    df = pd.read_csv(csv_file_path)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/day/all_stock_data.csv'
[2024-08-17T15:45:41.357+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=csv_to_parquet_minio_no_partition, task_id=csv_to_parquet_and_upload, run_id=manual__2024-08-17T15:45:39.428874+00:00, execution_date=20240817T154539, start_date=20240817T154540, end_date=20240817T154541
[2024-08-17T15:45:41.384+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 34 for task csv_to_parquet_and_upload ([Errno 2] No such file or directory: '/opt/airflow/data/day/all_stock_data.csv'; 3302)
[2024-08-17T15:45:41.401+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-17T15:45:41.415+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-17T15:45:41.417+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
